### ISSUE TITLE
Issue while saving data to S3 or GCS

### ISSUE THREAD

**Issue by iamdanishjaved** [ZuInnoTe/scrapy-contrib-bigexporters#8]
Here are the logs from my scraper, I am using python 3.9 and I have attached the snapshot from `settings.py` showing my changes to enable parquet feeds.
![image](https://user-images.githubusercontent.com/32013844/190431489-5c163505-7854-487e-9b11-6348ef327a58.png)
But below is the error in my logs showing. I have spent time to figure it out but what I found the reason is that it is creating and temporary file `'C:\\Users\\user_name\\AppData\\Local\\Temp\\feed-7xkqk0gn'` and the file is opened by an object and then another object from `site-packages\fastparquet\writer.py` tries to open and write data in it.

`2022-09-15 19:27:50,409 - engine - scrapy.core.engine - INFO - Closing spider (finished)
2022-09-15 19:27:50,423 - signal - scrapy.utils.signal - ERROR - Error caught on signal handler: <bound method FeedExporter.close_spider of <scrapy.extensions.feedexport.FeedExporter object at 0x00000201E5BB5D60>>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\scrapy\utils\defer.py", line 169, in maybeDeferred_coro
    result = f(*args, **kw)
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\scrapy\extensions\feedexport.py", line 348, in close_spider
    d = self._close_slot(slot, spider)
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\scrapy\extensions\feedexport.py", line 357, in _close_slot
    slot.finish_exporting()
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\scrapy\extensions\feedexport.py", line 281, in finish_exporting
    self.exporter.finish_exporting()
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\zuinnote\scrapy\contrib\bigexporters.py", line 318, in finish_exporting
    self._flush_table()
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\zuinnote\scrapy\contrib\bigexporters.py", line 383, in _flush_table
    fp_write(self.file.name, self.df,append=papp,compression=self.pq_compression,has_nulls=self.pq_hasnulls,write_index=self.pq_writeindex,file_scheme="simple",object_encoding=self.pq_objectencoding,times=self.pq_times,row_group_offsets=self.pq_rowgroupoffset)
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\fastparquet\writer.py", line 1231, in write
    write_simple(filename, data, fmd,
  File "C:\ProgramData\Anaconda3\envs\scraping9\lib\site-packages\fastparquet\writer.py", line 880, in write_simple
    with open_with(fn, mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user_name\\AppData\\Local\\Temp\\feed-7xkqk0gn'`
![image](https://user-images.githubusercontent.com/32013844/190433408-a18d5bfc-ba0d-44c0-b284-3591351a64e9.png)

I could not find the solution to this yet. This is happening when I tried to save feed on S3 or GCS.
For S3 I have tried the exact path mentioned [here](https://github.com/ZuInnoTe/scrapy-contrib-bigexporters/blob/main/docs/parquet.rst) but that didn't help.
![image](https://user-images.githubusercontent.com/32013844/190433020-6c75cc29-bb99-44b3-bd1e-aa0c35a22f5a.png)

**Comment by jornfranke** [comment]
Can you store data with the in-built scrapy plugins? E.g.  CSV to S3 or GCS? The plugin itself does not manage the storing to S3 and GCS - this is delegated to Scrapy.

**Comment by jornfranke** [comment]
Which Scrapy version?

**Comment by jornfranke** [comment]
And does it work if you save the file just locally?

**Comment by jornfranke** [comment]
sorry for so many question. I tested to save the file to s3 and it worked. However, I did not test under Windows unfortunately. The S3/GCS part though is done by Scrapy and it could be a bug there. It could be also that an antivirus solution blocks the file.

**Comment by iamdanishjaved** [comment]
Thank you responding, the answers to our questions:

1. Yes I can save CSV feeds to S3 and GCS.
2. Scrapy==1.5.0
3. Yes, it is working fine locally.
4. Ok, maybe you are right, let me test in Linux and will share the status.

I spent hours in debugging the code and I found it permission error for the file it's trying to open which is already occupied from another object in `writer.py`

**Comment by jornfranke** [comment]
thanks for all the time investing.
One could also try to update the fastparquet version to the latest one.

**Comment by iamdanishjaved** [comment]
Thank you for your responses, I tried this on Linux and it's saving data to GCS now.
`fastparquet` has some issues on windows.
